### PR TITLE
(non) working example

### PR DESCRIPTION
**Pull request by jacobrosenthal**

### CODE REVIEW

**Comment by shurcooL** [comment]
Thank you @jacobrosenthal for this reproduce case, it has helped me figure out where the issue was. I've opened #9 to track it.

I'll close this for now since we need to resolve #9 first. But I will consider re-adding a pre-made example like this after that. Thanks!

**Comment by jacobrosenthal** [comment]
Im not sure how hacky that is long run, but it does work. I added to the example, not sure why this shouldn't be merged then?

**Comment by jacobrosenthal** [comment]
No wait, I see it only works when I run wd, but not when I set to the bundle exec to wd...

**Comment by shurcooL** [comment]
It should work in the bundle too. Which folder did you put `wd` in? It should be inside MacOS, same as the Go binary.

**Comment by jacobrosenthal** [comment]
Check out my pr branch
https://github.com/jacobrosenthal/trayhost/tree/example

**Pull request closed without merging**
